### ISSUE TITLE
Implement lagrange_nodes using entity ordering?

### ISSUE THREAD

**Issue by jhale** [finite-element/finite-element-course#11]
My experience teaching the part of the course on constructing local entity to local dof map is that it's a bit unsatisfactory, particularly the use of the node entity predicate. 

Would it be best for students to implement the Lagrange nodes in the entity ordering from the start? Although this superior route is suggested in the notes, it is difficult to run the class with students split across two solution techniques.

**Comment by dham** [comment]
I think this is reasonable. I've changed the instructions to tell them to do this.
