### ISSUE TITLE
cant commit changes to my repository

### ISSUE THREAD

**Issue by Ismail1993** [finite-element/finite-element-course#3]
when i go for it by typing the following "git commit -am "implemented integrate" " I get the following thrown back at me

fatal: Unable to create '/Users/Ibrahim/finite-element-course/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

any helps?

**Comment by dham** [comment]
Well the error message you posted tells you what to do. First make sure that you haven't got another git running somewhere (if you've logged out of the machine then you've pretty much guaranteed that there aren't two git processes running at once). If you still get the error, then the message above tells you to remove the lock file and try again. You would remove the lock file using:
```
rm /Users/Ibrahim/finite-element-course/.git/index.lock
```
